### ISSUE TITLE
java.lang.NoClassDefFoundError: de/schlichtherle/io/File

### ISSUE THREAD

**Issue by fperie** [jbosstools/jbosstools-server#621]
Hello , 

I'm unable to start my JBOSS EAP 7 server into Eclipse. 

Currently , I'm facing a `NoClassDefFoundError`. 

Following the stacktrace : 
`!MESSAGE An internal error occurred during: "Starting JBoss EAP 7.1".
!STACK 0
java.lang.NoClassDefFoundError: de/schlichtherle/io/File
	at org.jboss.ide.eclipse.as.core.server.internal.extendedproperties.JBoss70DefaultLaunchArguments.getJBossJavaFlags(JBoss70DefaultLaunchArguments.java:72)
	at org.jboss.ide.eclipse.as.core.server.internal.extendedproperties.JBoss71DefaultLaunchArguments.getJBossJavaFlags(JBoss71DefaultLaunchArguments.java:32)
	at org.jboss.ide.eclipse.as.core.server.internal.extendedproperties.JBoss70DefaultLaunchArguments.getStartDefaultVMArgs(JBoss70DefaultLaunchArguments.java:55)
	at org.jboss.ide.eclipse.as.core.server.internal.extendedproperties.Wildfly80DefaultLaunchArguments.getStartDefaultVMArgs(Wildfly80DefaultLaunchArguments.java:25)
	at org.jboss.ide.eclipse.as.core.server.internal.launch.configuration.AbstractStartLaunchConfigurator.getDefaultVMArguments(AbstractStartLaunchConfigurator.java:142)
	at org.jboss.ide.eclipse.as.core.server.internal.launch.configuration.AbstractStartLaunchConfigurator.doConfigure(AbstractStartLaunchConfigurator.java:69)
	at org.jboss.ide.eclipse.as.wtp.core.server.launch.LaunchConfiguratorWithOverrides.configure(LaunchConfiguratorWithOverrides.java:55)
	at org.jboss.tools.as.core.server.controllable.subsystems.internal.LocalJBossLaunchController.setupLaunchConfiguration(LocalJBossLaunchController.java:59)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ControllableServerBehavior.setupLaunchConfiguration(ControllableServerBehavior.java:131)
	at org.jboss.tools.as.core.server.controllable.internal.DeployableServerBehavior.setupLaunchConfiguration(DeployableServerBehavior.java:38)
	at org.eclipse.wst.server.core.internal.Server.setupLaunchConfiguration(Server.java:1677)
	at org.eclipse.wst.server.core.internal.Server.getLaunchConfiguration(Server.java:1771)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3561)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3504)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:379)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**CURRENT WORK ENVIRONMENT : **

- Eclipse 4.11 : [Platform Runtime Binary + JDT binary](https://download.eclipse.org/eclipse/downloads/drops4/R-4.11-201903070500/)

- Jboss Tools Installation using this [update site](http://download.jboss.org/jbosstools/photon/development/updates/)

**WORKAROUND**

After many investigations, I was not able to start my server. 
The only workaround that I've found was to remove the line : 

`Bundle-ActivationPolicy: lazy` in the **MANIFEST.MF** on the plugin **org.jboss.ide.eclipse.archives.core_3.6.202.v20181011-1445**

My idea was to force the loading of all the required bundle + entry classpath

**Comment by jkopriva** [comment]
Hi @fperie, which java version are you using and also OS? Thanks!

**Comment by fperie** [comment]
Hello,
Eclipse runs under java 8

Thanks a lot,
Fabien

Le mar. 7 mai 2019 à 19:42, Josef Kopriva <notifications@github.com> a
écrit :

**Comment by jkopriva** [comment]
Hi @fperie, 

sorry for delay :(
I have tried it and it works for me. Which operating system are you using?
And also do you have configured EAP 7.1 or you just using defaults?
What parameters do you have in Runtime Configuration for server?

Thank you!
Josef

**Comment by robstryker** [comment]
There is a very clear bug in JBoss70DefaultLaunchArguments.java, but it is not the true cause of this bug.

it was introduced 2 years ago. This class is only used when forming the launch arguments for jboss 7.0. Even jboss 7.1 uses a different class. EAP 7.x should also be using a different class: JBossEAP70ExtendedProperties.java

The bug is that this class is trying to use File.separatorCharacter:  char sep = File.separatorChar;

But the class has imported the wrong File class.  It has imported the File class from project-archives and its dependency, truezip.  I have no idea why it's not resolving for user. It should. 

However this raises another questions:  
   User is trying to create an "EAP 7.x" server type, but it is clearly using the jboss-as-7.x launch args class. This is almost impossible, unless the user used "JBoss 7.0" server type to create their EAP server adapter and then ignored all errors. 

In the class that creates "extended properties" for each server type,  we can see the following:
                       if( SERVER_AS_70.equals(typeId) || AS_70.equals(typeId))
                                return new JBossAS7ExtendedProperties(adaptable);
                        if( SERVER_AS_71.equals(typeId) || AS_71.equals(typeId))
                                return new JBossAS710ExtendedProperties(adaptable);
               // trimmed for brevity
                        if( SERVER_EAP_70.equals(typeId) || EAP_70.equals(typeId))
                                return new JBossEAP70ExtendedProperties(adaptable);
                        if( SERVER_EAP_71.equals(typeId) || EAP_71.equals(typeId))
                                return new JBossEAP71ExtendedProperties(adaptable);
                        if( SERVER_EAP_72.equals(typeId) || EAP_72.equals(typeId))
                                return new JBossEAP72ExtendedProperties(adaptable);


Clearly, the stacktrace shows it is creating a JBossAS7ExtendedProperties, and not one of the EAP classes. This means the server adapter  must be of the normal JBoss type, and not the EAP type. So this part would be user-error, unless his server type was created via some automatic process?

**Comment by robstryker** [comment]
https://github.com/jbosstools/jbosstools-server/pull/625

**Comment by robstryker** [comment]
Closing this issue as cannot replicate
